image: gitpod/workspace-full

tasks:
  - init: |
      # Install npm dependencies
      npm install

      #Install Lambdatest Cloud
      npm install -g lambdatest-cypress-cli

      # Run Cypress tests with Lambdatest Cloud
      lambdatest-cypress run